# Generated by Django 5.1.3 on 2024-11-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
